### ISSUE TITLE
Fix table getting foreign keys

### ISSUE THREAD

**Issue by AmraniCh** [IbraheemAredda/DatabaseSchemaDesigner#1]
Little change to `src/models/table/getColumns()` function, checking if the table column has a foreign key before referencing the column.
My change 👍

```php
# Retrieve details
if (!empty($details = QueryHelper::exec_query(QueryHelper::get_fk_details($col->name, $this->name, $this->database), $this->connection))){
       # Reconstruct the column
       $col = new ReferenceColumn($col, $details[0]['REF_TABLE'], $details[0]['REF_COLUMN']);
}
```

**Comment by ghost** [comment]
> Little change to [src/models/table/getColumns()] function, checking if the table column has a foreign key before referencing the column.
> My change 👍
> 
> ```
> # Retrieve details
> if (!empty($details = QueryHelper::exec_query(QueryHelper::get_fk_details($col->name, $this->name, $this->database), $this->connection))){
>        # Reconstruct the column
>        $col = new ReferenceColumn($col, $details[0]['REF_TABLE'], $details[0]['REF_COLUMN']);
> }
> ```

thanks for reporting,
this checking is unnecessary, because there's already a test above, it checks if the column is a foreign key like so..
<code>if (strpos ($row["COLUMN_KEY"], 'MUL') !== false)</code>
if that test passes, be sure that <code>$details</code> <b>will never be empty</b>, so there is no need to repeat a needless check.

**Comment by AmraniCh** [comment]
Please notice that if the table engine is different than `EngineDB`, the `QueryHelper::get_fk_details()` is will return an empty array, so I guess you have two solutions here.
the first is to check if the returned array is empty or not, the second is check before if the table engine is `EngineDB`.
Not all the storage engines support the foreign key feature, so be careful.
`Note`: tested with the `MyISAM `engine.
